### PR TITLE
Robust ZonedTimestamp fixer

### PR DESCRIPTION
**Pull request by GearsAD**
Robust regex+function for cleaning up ZonedTimestamps from Neo4J and other places where it experiences formatting alchemy.

For a test, try this:
```julia
using TimeZones
s = [
"2020-08-12T12:00Z",  #Johan's test case
"2020-08-11T04:05:59-04:00",
"2020-08-11T04:05:59Z",
"2020-08-11T04:05:59.8-04:00",
"2020-08-11T04:05:59.82-04:00",
"2020-08-11T04:05:59.820-04:00",
"2020-08-11T04:05:59.8201-04:00"]

function _fixSubseconds(a)
    length(a) == 4 && return a[1:3]*".000"*a[4]
    frac = a[5:length(a)-1]
    frac = length(frac) > 3 ? frac[1:3] : frac*'0'^(3-length(frac))
    return a[1:4]*frac*a[length(a)]
end

function getStandardZDTString(stringTimestamp::String)
    # Additional check+fix for the ultraweird "2020-08-12T12:00Z"
    ts = replace(stringTimestamp, r"T(\d\d):(\d\d)(Z|z|\+|-)" => s"T\1:\2:00.000\3")

    # This is finding :59Z or :59.82-05:00 and fixing it to always have 3 subsecond digits.
    # Temporary fix until TimeZones.jl gets an upstream fix.
    return replace(ts, r":\d\d(\.\d+)?(Z|z|\+|-)" => _fixSubseconds)
end

for m in s
    print(getStandardZDTString(m)*"\r\n")
end
```

### CODE REVIEW

**Comment by Affie** [comment]
Don't think this one will work:
"2020-08-12T12:00Z"

**Comment by dehann** [comment]
@GearsAD that's an awesome new label!

**Comment by dehann** [comment]
ref JuliaTime/TimeZones.jl#83

**Comment by GearsAD** [comment]
This is timestamp insanity haha. Neo4j (or Neo4j.jl) is coming back with:
```
props = ((((result.results[1])["data"])[1])["row"])[1] = Dict{String,Any}("softtype" => "ContinuousScalar","label" => "x1","smallData" => "{}","_type" => "DFGVariable{ContinuousScalar}","nstime" => 0,"tags" => Any["VARIABLE"],"solvable" => 1,"timestamp" => "2020-08-12T12:00Z")
```

That's not even ISO8601 (as far as I know). I _hope_ this is magically fixed in Neo4j 4.0.

Right, will add another boundary condition in for that. v0.11 we're going to have to revisit all this :+1:

**Comment by GearsAD** [comment]
Okay @Affie, that should be the last of them!

**Comment by Affie** [comment]
PR looks good to me. 

I see Neo4j 4 also save as:

2015-07-21T21:40:32.142+01:00
2015-07-21T21:40:32.142Z
2015-01-01T21:40:32-01:00
2015-07-21T21:40-01:30
2015-07-20T21:40-02:00
2015-07-21T21:00+18:00
2015-07-21T21:40:32.142+01:00[Europe/London]
2015-07-21T21:40:32.142-04:00[America/New_York]

https://neo4j.com/docs/cypher-manual/current/functions/temporal/datetime/

The method I spoke about the other day woudl be something like this, but it won't parse smaller than milliseconds:
```julia 
function string2ZonedTimeStamp(stringTimestamp) 
  ss = split(stringTimestamp, r"(?=[-+Zz](?!.*[-+Zz]))")
  return ZonedDateTime(DateTime(ss[1]), TimeZone(ss[2]))
end
```

**Comment by GearsAD** [comment]
Next week let's plan some long term serialization work, will merge this for v0.10

**Pull request merged**
