### PR TITLE
minimum GraphPlot = "0.4"

### PR DESCRIPTION
**Pull request by dehann**
Problem with compat, see JuliaRobotics/AprilTags.jl#57

This breaks Pkg compat quite badly, not sure where the issue is coming from.

just cc'ing @Affie on this too

### CODE REVIEW

**Comment by Affie** [comment]
Hi, GraphPlot is an optional requirement with Requires.jl. The last time I checked there was no way to specify optional Requires.jl compact. see https://github.com/JuliaPackaging/Requires.jl/issues/82 and https://github.com/JuliaPackaging/Requires.jl/issues/3

**Review by Affie — CHANGES_REQUESTED** [review]
GraphPlot is not in deps but a Requires.jl import, also see this comment: https://github.com/JuliaPackaging/Requires.jl/issues/3#issuecomment-529830411

**Comment by Affie** [comment]
I previously thought of waiting for something like this (https://github.com/JuliaLang/Pkg.jl/issues/1285) to be implemented

**Comment by dehann** [comment]
that's not the issue here.  i was trying to fix a compat issue by specifying a minimum, but not necessary.  this is a new non-resolvable set of pkg compat issue.

**Pull request closed without merging**
