### PR TITLE
Deleting v0.10 deprecations

### LINKED ISSUE #544: Remove deprecated factor types and logic
Such as https://github.com/JuliaRobotics/DistributedFactorGraphs.jl/pull/537/files/830224174804dc5ad469981d33f2e2b011019d44#diff-5f972abb36e8a091875a1a0c90cc5f21R138

### PR DESCRIPTION
**Pull request by GearsAD**
Fixes #544

### CODE REVIEW

**Comment by GearsAD** [comment]
Downstream is failing, need to check out what's happening there.

**Comment by Affie** [comment]
I think it's ok if it stays in one more cycle, so we shouldn't let it hold us up. 
Lets at least hold up on this pr until downstream is updated?

**Comment by Affie** [comment]
I saw a few more and added them

**Comment by dehann** [comment]
I'd ask for some help cleaning up the downstream deprecations please, keeping up with IIF, RoME, Caesar, RoMEPlotting alone is a lot of work.

**Pull request merged**
