### PR TITLE
Precompile CGDFG based on ENV variable

### PR DESCRIPTION
**Pull request by Affie**
Temporary fix for #554
This is not really a good idea. It looks like new updates to Pkg might provide a better solution.
Note that ENV variable DFG_USE_CGDFG should be seen as a permanent feature setting as CGDF will be precompiled into the cache.

### CODE REVIEW

**Comment by GearsAD** [comment]
I think this is good - if you want to disable/enable this, you need to remove and reload DFG with that flag set. 

We can revisit when Pkg functionality exists.

**Comment by dehann** [comment]
I think there is a trick that Tim Holy suggested (as usual) -- somewhere out there in the ecosystem comments:
```julia
ENV = ENV["DFG_USE_CGDFG"]
using Pkg
Pkg.build("DistributedFactorGraphs")
using DistributedFactorGraphs
```

**Comment by Affie** [comment]
```julia
julia> ENV["DFG_USE_CGDFG"]="true"
julia> Base.compilecache(Base.PkgId(DistributedFactorGraphs))
[ Info: Precompiling DistributedFactorGraphs [b5cc3c7e-6572-11e9-2517-99fb8daf2f04]
[ Info: Detected ENV["DFG_USE_CGDFG"]: Including optional CloudGraphsDFG (LGPL) Driver
```

**Comment by Affie** [comment]
`Base.compilecache(Base.PkgId(DistributedFactorGraphs))` seems to not work with Revise

**Pull request merged**
