### PR TITLE
fix integration tests 354

### PR DESCRIPTION
**Pull request by dehann**
fixes #354

### CODE REVIEW

**Comment by andreasnoack** [comment]
# [Codecov](https://codecov.io/gh/JuliaRobotics/DistributedFactorGraphs.jl/pull/356?src=pr&el=h1) Report
> Merging [#356](https://codecov.io/gh/JuliaRobotics/DistributedFactorGraphs.jl/pull/356?src=pr&el=desc) into [master](https://codecov.io/gh/JuliaRobotics/DistributedFactorGraphs.jl/commit/0b9efc499c9dfb2b57d961a48bf35b8cb9bdbcda&el=desc) will **not change** coverage by `%`.
> The diff coverage is `n/a`.

[Impacted file tree graph](https://codecov.io/gh/JuliaRobotics/DistributedFactorGraphs.jl/pull/356?src=pr&el=tree)

```diff
@@           Coverage Diff           @@
##           master     #356   +/-   ##
=======================================
  Coverage   49.68%   49.68%           
=======================================
  Files          34       34           
  Lines        1731     1731           
=======================================
  Hits          860      860           
  Misses        871      871           
```



------

[Continue to review full report at Codecov](https://codecov.io/gh/JuliaRobotics/DistributedFactorGraphs.jl/pull/356?src=pr&el=continue).
> **Legend** - [Click here to learn more](https://docs.codecov.io/docs/codecov-delta)
> `Δ = absolute <relative> (impact)`, `ø = not affected`, `? = missing data`
> Powered by [Codecov](https://codecov.io/gh/JuliaRobotics/DistributedFactorGraphs.jl/pull/356?src=pr&el=footer). Last update [0b9efc4...310d1eb](https://codecov.io/gh/JuliaRobotics/DistributedFactorGraphs.jl/pull/356?src=pr&el=lastupdated). Read the [comment docs](https://docs.codecov.io/docs/pull-request-comments).

**Comment by andreasnoack** [comment]
# [Codecov](https://codecov.io/gh/JuliaRobotics/DistributedFactorGraphs.jl/pull/356?src=pr&el=h1) Report
> Merging [#356](https://codecov.io/gh/JuliaRobotics/DistributedFactorGraphs.jl/pull/356?src=pr&el=desc) into [master](https://codecov.io/gh/JuliaRobotics/DistributedFactorGraphs.jl/commit/0b9efc499c9dfb2b57d961a48bf35b8cb9bdbcda&el=desc) will **decrease** coverage by `0.02%`.
> The diff coverage is `n/a`.

[Impacted file tree graph](https://codecov.io/gh/JuliaRobotics/DistributedFactorGraphs.jl/pull/356?src=pr&el=tree)

```diff
@@            Coverage Diff             @@
##           master     #356      +/-   ##
==========================================
- Coverage   49.68%   49.65%   -0.03%     
==========================================
  Files          34       34              
  Lines        1731     1732       +1     
==========================================
  Hits          860      860              
- Misses        871      872       +1     
```



------

[Continue to review full report at Codecov](https://codecov.io/gh/JuliaRobotics/DistributedFactorGraphs.jl/pull/356?src=pr&el=continue).
> **Legend** - [Click here to learn more](https://docs.codecov.io/docs/codecov-delta)
> `Δ = absolute <relative> (impact)`, `ø = not affected`, `? = missing data`
> Powered by [Codecov](https://codecov.io/gh/JuliaRobotics/DistributedFactorGraphs.jl/pull/356?src=pr&el=footer). Last update [0b9efc4...938438a](https://codecov.io/gh/JuliaRobotics/DistributedFactorGraphs.jl/pull/356?src=pr&el=lastupdated). Read the [comment docs](https://docs.codecov.io/docs/pull-request-comments).

**Comment by andreasnoack** [comment]
# [Codecov](https://codecov.io/gh/JuliaRobotics/DistributedFactorGraphs.jl/pull/356?src=pr&el=h1) Report
> Merging [#356](https://codecov.io/gh/JuliaRobotics/DistributedFactorGraphs.jl/pull/356?src=pr&el=desc) into [master](https://codecov.io/gh/JuliaRobotics/DistributedFactorGraphs.jl/commit/0b9efc499c9dfb2b57d961a48bf35b8cb9bdbcda&el=desc) will **decrease** coverage by `0.02%`.
> The diff coverage is `n/a`.

[Impacted file tree graph](https://codecov.io/gh/JuliaRobotics/DistributedFactorGraphs.jl/pull/356?src=pr&el=tree)

```diff
@@            Coverage Diff             @@
##           master     #356      +/-   ##
==========================================
- Coverage   49.68%   49.65%   -0.03%     
==========================================
  Files          34       34              
  Lines        1731     1732       +1     
==========================================
  Hits          860      860              
- Misses        871      872       +1     
```



------

[Continue to review full report at Codecov](https://codecov.io/gh/JuliaRobotics/DistributedFactorGraphs.jl/pull/356?src=pr&el=continue).
> **Legend** - [Click here to learn more](https://docs.codecov.io/docs/codecov-delta)
> `Δ = absolute <relative> (impact)`, `ø = not affected`, `? = missing data`
> Powered by [Codecov](https://codecov.io/gh/JuliaRobotics/DistributedFactorGraphs.jl/pull/356?src=pr&el=footer). Last update [0b9efc4...938438a](https://codecov.io/gh/JuliaRobotics/DistributedFactorGraphs.jl/pull/356?src=pr&el=lastupdated). Read the [comment docs](https://docs.codecov.io/docs/pull-request-comments).

**Comment by andreasnoack** [comment]
# [Codecov](https://codecov.io/gh/JuliaRobotics/DistributedFactorGraphs.jl/pull/356?src=pr&el=h1) Report
> Merging [#356](https://codecov.io/gh/JuliaRobotics/DistributedFactorGraphs.jl/pull/356?src=pr&el=desc) into [master](https://codecov.io/gh/JuliaRobotics/DistributedFactorGraphs.jl/commit/0b9efc499c9dfb2b57d961a48bf35b8cb9bdbcda&el=desc) will **decrease** coverage by `0.02%`.
> The diff coverage is `n/a`.

[Impacted file tree graph](https://codecov.io/gh/JuliaRobotics/DistributedFactorGraphs.jl/pull/356?src=pr&el=tree)

```diff
@@            Coverage Diff             @@
##           master     #356      +/-   ##
==========================================
- Coverage   49.68%   49.65%   -0.03%     
==========================================
  Files          34       34              
  Lines        1731     1732       +1     
==========================================
  Hits          860      860              
- Misses        871      872       +1     
```



------

[Continue to review full report at Codecov](https://codecov.io/gh/JuliaRobotics/DistributedFactorGraphs.jl/pull/356?src=pr&el=continue).
> **Legend** - [Click here to learn more](https://docs.codecov.io/docs/codecov-delta)
> `Δ = absolute <relative> (impact)`, `ø = not affected`, `? = missing data`
> Powered by [Codecov](https://codecov.io/gh/JuliaRobotics/DistributedFactorGraphs.jl/pull/356?src=pr&el=footer). Last update [0b9efc4...95f36fe](https://codecov.io/gh/JuliaRobotics/DistributedFactorGraphs.jl/pull/356?src=pr&el=lastupdated). Read the [comment docs](https://docs.codecov.io/docs/pull-request-comments).

**Comment by andreasnoack** [comment]
# [Codecov](https://codecov.io/gh/JuliaRobotics/DistributedFactorGraphs.jl/pull/356?src=pr&el=h1) Report
> Merging [#356](https://codecov.io/gh/JuliaRobotics/DistributedFactorGraphs.jl/pull/356?src=pr&el=desc) into [master](https://codecov.io/gh/JuliaRobotics/DistributedFactorGraphs.jl/commit/0b9efc499c9dfb2b57d961a48bf35b8cb9bdbcda&el=desc) will **decrease** coverage by `0.02%`.
> The diff coverage is `n/a`.

[Impacted file tree graph](https://codecov.io/gh/JuliaRobotics/DistributedFactorGraphs.jl/pull/356?src=pr&el=tree)

```diff
@@            Coverage Diff             @@
##           master     #356      +/-   ##
==========================================
- Coverage   49.68%   49.65%   -0.03%     
==========================================
  Files          34       34              
  Lines        1731     1732       +1     
==========================================
  Hits          860      860              
- Misses        871      872       +1     
```



------

[Continue to review full report at Codecov](https://codecov.io/gh/JuliaRobotics/DistributedFactorGraphs.jl/pull/356?src=pr&el=continue).
> **Legend** - [Click here to learn more](https://docs.codecov.io/docs/codecov-delta)
> `Δ = absolute <relative> (impact)`, `ø = not affected`, `? = missing data`
> Powered by [Codecov](https://codecov.io/gh/JuliaRobotics/DistributedFactorGraphs.jl/pull/356?src=pr&el=footer). Last update [0b9efc4...95f36fe](https://codecov.io/gh/JuliaRobotics/DistributedFactorGraphs.jl/pull/356?src=pr&el=lastupdated). Read the [comment docs](https://docs.codecov.io/docs/pull-request-comments).

**Comment by andreasnoack** [comment]
# [Codecov](https://codecov.io/gh/JuliaRobotics/DistributedFactorGraphs.jl/pull/356?src=pr&el=h1) Report
> Merging [#356](https://codecov.io/gh/JuliaRobotics/DistributedFactorGraphs.jl/pull/356?src=pr&el=desc) into [master](https://codecov.io/gh/JuliaRobotics/DistributedFactorGraphs.jl/commit/0b9efc499c9dfb2b57d961a48bf35b8cb9bdbcda&el=desc) will **decrease** coverage by `0.02%`.
> The diff coverage is `n/a`.

[Impacted file tree graph](https://codecov.io/gh/JuliaRobotics/DistributedFactorGraphs.jl/pull/356?src=pr&el=tree)

```diff
@@            Coverage Diff             @@
##           master     #356      +/-   ##
==========================================
- Coverage   49.68%   49.65%   -0.03%     
==========================================
  Files          34       34              
  Lines        1731     1732       +1     
==========================================
  Hits          860      860              
- Misses        871      872       +1     
```



------

[Continue to review full report at Codecov](https://codecov.io/gh/JuliaRobotics/DistributedFactorGraphs.jl/pull/356?src=pr&el=continue).
> **Legend** - [Click here to learn more](https://docs.codecov.io/docs/codecov-delta)
> `Δ = absolute <relative> (impact)`, `ø = not affected`, `? = missing data`
> Powered by [Codecov](https://codecov.io/gh/JuliaRobotics/DistributedFactorGraphs.jl/pull/356?src=pr&el=footer). Last update [0b9efc4...c24f0a8](https://codecov.io/gh/JuliaRobotics/DistributedFactorGraphs.jl/pull/356?src=pr&el=lastupdated). Read the [comment docs](https://docs.codecov.io/docs/pull-request-comments).

**Comment by dehann** [comment]
closes #359

**Comment by dehann** [comment]
closes #355

**Pull request merged**
