### PR TITLE
Bugfixes for julia 1.6.0-beta1

### PR DESCRIPTION
**Pull request by Affie**

### CODE REVIEW

**Comment by dehann** [comment]
HI @Affie , just in case, dont wait on #730 -- if tests pass locally by you then merge this so work can continue on fixing JuliaRobotics/IncrementalInference.jl#1120

**Comment by Affie** [comment]
Ok, I’ll merge so long. It’s passing more than current master, but not everthing. I would have liked all to pass, but travis is too much of a pain.

**Comment by dehann** [comment]
also closes #728

**Comment by dehann** [comment]
also closes #725

**Pull request merged**
