### PR TITLE
As per discussion - Type on solverDict

### PR DESCRIPTION
**Pull request by GearsAD**

### CODE REVIEW

**Comment by dehann** [comment]
related to #237

**Comment by dehann** [comment]
FYI -- what was the discussion on types for `solverDict` (assuming its an issue somewhere)?  My feeling is still that we should not do this since softtype is specific to a variable and not the solverDict elements inside a variable.  If you want to change a variable type, you need to build a whole new factor graph.

**Comment by GearsAD** [comment]
Yes, if that's the case - "softtype is specific to a variable and not the solverDict elements inside a variable" - then my understanding is we merge #199 for v6.0 and this can be closed.

**Comment by GearsAD** [comment]
Actually, while we're here, let's just line that up

**Pull request closed without merging**
