### PR TITLE
Defensively implementing backticks on sentinel nodes (userId, robotId, sessionId)

### LINKED ISSUE #870: UserID must be backticked in Neo4jDFG
This allows userIDs to be free strings.

### PR DESCRIPTION
**Pull request by GearsAD**
Resolves #870

### CODE REVIEW

**Review by Affie — APPROVED** [review]
I just read through it, but LGTM

**Comment by Affie** [comment]
We should just bump the minor version.

**Comment by Affie** [comment]
Is it not a breaking change, so v0.19?

**Comment by jim-hill-r** [comment]
I'll do some tests this evening. My only immediate thought is what is actually stored in the db. The db doesn't store backticks right, it's just syntax for the query? That means it's non breaking yes?

**Comment by Affie** [comment]
I'll leave that up to you, happy either way.

**Comment by GearsAD** [comment]
This isn't a breaking change and it doesn't change how the data is persisted.

**Review by dehann — APPROVED** [review]
Thanks doing this Sam!

**Comment by dehann** [comment]
If not breaking then we can just do a patch release v0.18.3.

**Review by jim-hill-r — APPROVED** [review]

**Comment by jim-hill-r** [comment]
Testing looked great! I was able to run a hex and a solve with no problems using user "guest@navability.io". I then did a hex and solve with "jim@navability.io" and that also went well. I also did a bunch of AprilTag things via Introduction then checked the viz. Both fg and geometric work. Go forth and release the patch.

**Comment by GearsAD** [comment]
Great, merging and tagging!

**Pull request merged**
